import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "./components/header";
import Footer from "./components/footer";
import styles from "./page.module.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["cyrillic"],
});

export const metadata: Metadata = {
  title: "Q. Visit",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <div className={styles.container}>
          <Head></Head>
        </div>
        {children}
        <div className={styles.footContainer}>
          <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
